//
// Created by jachin on 2020/3/9.
//

#ifndef YOLO_DETECTOR_TEST_BASE_FEATURE_EXTRATOR_H
#define YOLO_DETECTOR_TEST_BASE_FEATURE_EXTRATOR_H





#endif //YOLO_DETECTOR_TEST_BASE_FEATURE_EXTRATOR_H
