// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imu.proto

#ifndef PROTOBUF_imu_2eproto__INCLUDED
#define PROTOBUF_imu_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "modules/common/proto/header.pb.h"
#include "modules/localization/proto/pose.pb.h"
// @@protoc_insertion_point(includes)

namespace apollo {
namespace localization {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_imu_2eproto();
void protobuf_AssignDesc_imu_2eproto();
void protobuf_ShutdownFile_imu_2eproto();

class CorrectedImu;

// ===================================================================

class CorrectedImu : public ::google::protobuf::Message {
 public:
  CorrectedImu();
  virtual ~CorrectedImu();

  CorrectedImu(const CorrectedImu& from);

  inline CorrectedImu& operator=(const CorrectedImu& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CorrectedImu& default_instance();

  void Swap(CorrectedImu* other);

  // implements Message ----------------------------------------------

  CorrectedImu* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CorrectedImu& from);
  void MergeFrom(const CorrectedImu& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.common.Header header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline const ::apollo::common::Header& header() const;
  inline ::apollo::common::Header* mutable_header();
  inline ::apollo::common::Header* release_header();
  inline void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.localization.Pose imu = 3;
  inline bool has_imu() const;
  inline void clear_imu();
  static const int kImuFieldNumber = 3;
  inline const ::apollo::localization::Pose& imu() const;
  inline ::apollo::localization::Pose* mutable_imu();
  inline ::apollo::localization::Pose* release_imu();
  inline void set_allocated_imu(::apollo::localization::Pose* imu);

  // @@protoc_insertion_point(class_scope:apollo.localization.CorrectedImu)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_imu();
  inline void clear_has_imu();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::common::Header* header_;
  ::apollo::localization::Pose* imu_;
  friend void  protobuf_AddDesc_imu_2eproto();
  friend void protobuf_AssignDesc_imu_2eproto();
  friend void protobuf_ShutdownFile_imu_2eproto();

  void InitAsDefaultInstance();
  static CorrectedImu* default_instance_;
};
// ===================================================================


// ===================================================================

// CorrectedImu

// optional .apollo.common.Header header = 1;
inline bool CorrectedImu::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CorrectedImu::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CorrectedImu::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CorrectedImu::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& CorrectedImu::header() const {
  // @@protoc_insertion_point(field_get:apollo.localization.CorrectedImu.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::apollo::common::Header* CorrectedImu::mutable_header() {
  set_has_header();
  if (header_ == NULL) header_ = new ::apollo::common::Header;
  // @@protoc_insertion_point(field_mutable:apollo.localization.CorrectedImu.header)
  return header_;
}
inline ::apollo::common::Header* CorrectedImu::release_header() {
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void CorrectedImu::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.CorrectedImu.header)
}

// optional .apollo.localization.Pose imu = 3;
inline bool CorrectedImu::has_imu() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CorrectedImu::set_has_imu() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CorrectedImu::clear_has_imu() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CorrectedImu::clear_imu() {
  if (imu_ != NULL) imu_->::apollo::localization::Pose::Clear();
  clear_has_imu();
}
inline const ::apollo::localization::Pose& CorrectedImu::imu() const {
  // @@protoc_insertion_point(field_get:apollo.localization.CorrectedImu.imu)
  return imu_ != NULL ? *imu_ : *default_instance_->imu_;
}
inline ::apollo::localization::Pose* CorrectedImu::mutable_imu() {
  set_has_imu();
  if (imu_ == NULL) imu_ = new ::apollo::localization::Pose;
  // @@protoc_insertion_point(field_mutable:apollo.localization.CorrectedImu.imu)
  return imu_;
}
inline ::apollo::localization::Pose* CorrectedImu::release_imu() {
  clear_has_imu();
  ::apollo::localization::Pose* temp = imu_;
  imu_ = NULL;
  return temp;
}
inline void CorrectedImu::set_allocated_imu(::apollo::localization::Pose* imu) {
  delete imu_;
  imu_ = imu;
  if (imu) {
    set_has_imu();
  } else {
    clear_has_imu();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.CorrectedImu.imu)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace localization
}  // namespace apollo

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_imu_2eproto__INCLUDED
