// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: localization.proto

#ifndef PROTOBUF_localization_2eproto__INCLUDED
#define PROTOBUF_localization_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "modules/common/proto/header.pb.h"
#include "modules/localization/proto/pose.pb.h"
#include "modules/common/proto/geometry.pb.h"
#include "modules/common/proto/pnc_point.pb.h"
#include "modules/localization/proto/localization_status.pb.h"
// @@protoc_insertion_point(includes)

namespace apollo {
namespace localization {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_localization_2eproto();
void protobuf_AssignDesc_localization_2eproto();
void protobuf_ShutdownFile_localization_2eproto();

class Uncertainty;
class LocalizationEstimate;
class LocalizationStatus;

enum MeasureState {
  OK = 0,
  WARNNING = 1,
  ERROR = 2,
  CRITICAL_ERROR = 3,
  FATAL_ERROR = 4
};
bool MeasureState_IsValid(int value);
const MeasureState MeasureState_MIN = OK;
const MeasureState MeasureState_MAX = FATAL_ERROR;
const int MeasureState_ARRAYSIZE = MeasureState_MAX + 1;

const ::google::protobuf::EnumDescriptor* MeasureState_descriptor();
inline const ::std::string& MeasureState_Name(MeasureState value) {
  return ::google::protobuf::internal::NameOfEnum(
    MeasureState_descriptor(), value);
}
inline bool MeasureState_Parse(
    const ::std::string& name, MeasureState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MeasureState>(
    MeasureState_descriptor(), name, value);
}
// ===================================================================

class Uncertainty : public ::google::protobuf::Message {
 public:
  Uncertainty();
  virtual ~Uncertainty();

  Uncertainty(const Uncertainty& from);

  inline Uncertainty& operator=(const Uncertainty& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Uncertainty& default_instance();

  void Swap(Uncertainty* other);

  // implements Message ----------------------------------------------

  Uncertainty* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Uncertainty& from);
  void MergeFrom(const Uncertainty& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.common.Point3D position_std_dev = 1;
  inline bool has_position_std_dev() const;
  inline void clear_position_std_dev();
  static const int kPositionStdDevFieldNumber = 1;
  inline const ::apollo::common::Point3D& position_std_dev() const;
  inline ::apollo::common::Point3D* mutable_position_std_dev();
  inline ::apollo::common::Point3D* release_position_std_dev();
  inline void set_allocated_position_std_dev(::apollo::common::Point3D* position_std_dev);

  // optional .apollo.common.Point3D orientation_std_dev = 2;
  inline bool has_orientation_std_dev() const;
  inline void clear_orientation_std_dev();
  static const int kOrientationStdDevFieldNumber = 2;
  inline const ::apollo::common::Point3D& orientation_std_dev() const;
  inline ::apollo::common::Point3D* mutable_orientation_std_dev();
  inline ::apollo::common::Point3D* release_orientation_std_dev();
  inline void set_allocated_orientation_std_dev(::apollo::common::Point3D* orientation_std_dev);

  // optional .apollo.common.Point3D linear_velocity_std_dev = 3;
  inline bool has_linear_velocity_std_dev() const;
  inline void clear_linear_velocity_std_dev();
  static const int kLinearVelocityStdDevFieldNumber = 3;
  inline const ::apollo::common::Point3D& linear_velocity_std_dev() const;
  inline ::apollo::common::Point3D* mutable_linear_velocity_std_dev();
  inline ::apollo::common::Point3D* release_linear_velocity_std_dev();
  inline void set_allocated_linear_velocity_std_dev(::apollo::common::Point3D* linear_velocity_std_dev);

  // optional .apollo.common.Point3D linear_acceleration_std_dev = 4;
  inline bool has_linear_acceleration_std_dev() const;
  inline void clear_linear_acceleration_std_dev();
  static const int kLinearAccelerationStdDevFieldNumber = 4;
  inline const ::apollo::common::Point3D& linear_acceleration_std_dev() const;
  inline ::apollo::common::Point3D* mutable_linear_acceleration_std_dev();
  inline ::apollo::common::Point3D* release_linear_acceleration_std_dev();
  inline void set_allocated_linear_acceleration_std_dev(::apollo::common::Point3D* linear_acceleration_std_dev);

  // optional .apollo.common.Point3D angular_velocity_std_dev = 5;
  inline bool has_angular_velocity_std_dev() const;
  inline void clear_angular_velocity_std_dev();
  static const int kAngularVelocityStdDevFieldNumber = 5;
  inline const ::apollo::common::Point3D& angular_velocity_std_dev() const;
  inline ::apollo::common::Point3D* mutable_angular_velocity_std_dev();
  inline ::apollo::common::Point3D* release_angular_velocity_std_dev();
  inline void set_allocated_angular_velocity_std_dev(::apollo::common::Point3D* angular_velocity_std_dev);

  // @@protoc_insertion_point(class_scope:apollo.localization.Uncertainty)
 private:
  inline void set_has_position_std_dev();
  inline void clear_has_position_std_dev();
  inline void set_has_orientation_std_dev();
  inline void clear_has_orientation_std_dev();
  inline void set_has_linear_velocity_std_dev();
  inline void clear_has_linear_velocity_std_dev();
  inline void set_has_linear_acceleration_std_dev();
  inline void clear_has_linear_acceleration_std_dev();
  inline void set_has_angular_velocity_std_dev();
  inline void clear_has_angular_velocity_std_dev();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::common::Point3D* position_std_dev_;
  ::apollo::common::Point3D* orientation_std_dev_;
  ::apollo::common::Point3D* linear_velocity_std_dev_;
  ::apollo::common::Point3D* linear_acceleration_std_dev_;
  ::apollo::common::Point3D* angular_velocity_std_dev_;
  friend void  protobuf_AddDesc_localization_2eproto();
  friend void protobuf_AssignDesc_localization_2eproto();
  friend void protobuf_ShutdownFile_localization_2eproto();

  void InitAsDefaultInstance();
  static Uncertainty* default_instance_;
};
// -------------------------------------------------------------------

class LocalizationEstimate : public ::google::protobuf::Message {
 public:
  LocalizationEstimate();
  virtual ~LocalizationEstimate();

  LocalizationEstimate(const LocalizationEstimate& from);

  inline LocalizationEstimate& operator=(const LocalizationEstimate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LocalizationEstimate& default_instance();

  void Swap(LocalizationEstimate* other);

  // implements Message ----------------------------------------------

  LocalizationEstimate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LocalizationEstimate& from);
  void MergeFrom(const LocalizationEstimate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.common.Header header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline const ::apollo::common::Header& header() const;
  inline ::apollo::common::Header* mutable_header();
  inline ::apollo::common::Header* release_header();
  inline void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.localization.Pose pose = 2;
  inline bool has_pose() const;
  inline void clear_pose();
  static const int kPoseFieldNumber = 2;
  inline const ::apollo::localization::Pose& pose() const;
  inline ::apollo::localization::Pose* mutable_pose();
  inline ::apollo::localization::Pose* release_pose();
  inline void set_allocated_pose(::apollo::localization::Pose* pose);

  // optional .apollo.localization.Uncertainty uncertainty = 3;
  inline bool has_uncertainty() const;
  inline void clear_uncertainty();
  static const int kUncertaintyFieldNumber = 3;
  inline const ::apollo::localization::Uncertainty& uncertainty() const;
  inline ::apollo::localization::Uncertainty* mutable_uncertainty();
  inline ::apollo::localization::Uncertainty* release_uncertainty();
  inline void set_allocated_uncertainty(::apollo::localization::Uncertainty* uncertainty);

  // optional double measurement_time = 4;
  inline bool has_measurement_time() const;
  inline void clear_measurement_time();
  static const int kMeasurementTimeFieldNumber = 4;
  inline double measurement_time() const;
  inline void set_measurement_time(double value);

  // repeated .apollo.common.TrajectoryPoint trajectory_point = 5;
  inline int trajectory_point_size() const;
  inline void clear_trajectory_point();
  static const int kTrajectoryPointFieldNumber = 5;
  inline const ::apollo::common::TrajectoryPoint& trajectory_point(int index) const;
  inline ::apollo::common::TrajectoryPoint* mutable_trajectory_point(int index);
  inline ::apollo::common::TrajectoryPoint* add_trajectory_point();
  inline const ::google::protobuf::RepeatedPtrField< ::apollo::common::TrajectoryPoint >&
      trajectory_point() const;
  inline ::google::protobuf::RepeatedPtrField< ::apollo::common::TrajectoryPoint >*
      mutable_trajectory_point();

  // optional .apollo.localization.MsfStatus msf_status = 6;
  inline bool has_msf_status() const;
  inline void clear_msf_status();
  static const int kMsfStatusFieldNumber = 6;
  inline const ::apollo::localization::MsfStatus& msf_status() const;
  inline ::apollo::localization::MsfStatus* mutable_msf_status();
  inline ::apollo::localization::MsfStatus* release_msf_status();
  inline void set_allocated_msf_status(::apollo::localization::MsfStatus* msf_status);

  // optional .apollo.localization.MsfSensorMsgStatus sensor_status = 7;
  inline bool has_sensor_status() const;
  inline void clear_sensor_status();
  static const int kSensorStatusFieldNumber = 7;
  inline const ::apollo::localization::MsfSensorMsgStatus& sensor_status() const;
  inline ::apollo::localization::MsfSensorMsgStatus* mutable_sensor_status();
  inline ::apollo::localization::MsfSensorMsgStatus* release_sensor_status();
  inline void set_allocated_sensor_status(::apollo::localization::MsfSensorMsgStatus* sensor_status);

  // @@protoc_insertion_point(class_scope:apollo.localization.LocalizationEstimate)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_pose();
  inline void clear_has_pose();
  inline void set_has_uncertainty();
  inline void clear_has_uncertainty();
  inline void set_has_measurement_time();
  inline void clear_has_measurement_time();
  inline void set_has_msf_status();
  inline void clear_has_msf_status();
  inline void set_has_sensor_status();
  inline void clear_has_sensor_status();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::common::Header* header_;
  ::apollo::localization::Pose* pose_;
  ::apollo::localization::Uncertainty* uncertainty_;
  double measurement_time_;
  ::google::protobuf::RepeatedPtrField< ::apollo::common::TrajectoryPoint > trajectory_point_;
  ::apollo::localization::MsfStatus* msf_status_;
  ::apollo::localization::MsfSensorMsgStatus* sensor_status_;
  friend void  protobuf_AddDesc_localization_2eproto();
  friend void protobuf_AssignDesc_localization_2eproto();
  friend void protobuf_ShutdownFile_localization_2eproto();

  void InitAsDefaultInstance();
  static LocalizationEstimate* default_instance_;
};
// -------------------------------------------------------------------

class LocalizationStatus : public ::google::protobuf::Message {
 public:
  LocalizationStatus();
  virtual ~LocalizationStatus();

  LocalizationStatus(const LocalizationStatus& from);

  inline LocalizationStatus& operator=(const LocalizationStatus& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LocalizationStatus& default_instance();

  void Swap(LocalizationStatus* other);

  // implements Message ----------------------------------------------

  LocalizationStatus* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LocalizationStatus& from);
  void MergeFrom(const LocalizationStatus& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.common.Header header = 1;
  inline bool has_header() const;
  inline void clear_header();
  static const int kHeaderFieldNumber = 1;
  inline const ::apollo::common::Header& header() const;
  inline ::apollo::common::Header* mutable_header();
  inline ::apollo::common::Header* release_header();
  inline void set_allocated_header(::apollo::common::Header* header);

  // optional .apollo.localization.MeasureState fusion_status = 2;
  inline bool has_fusion_status() const;
  inline void clear_fusion_status();
  static const int kFusionStatusFieldNumber = 2;
  inline ::apollo::localization::MeasureState fusion_status() const;
  inline void set_fusion_status(::apollo::localization::MeasureState value);

  // optional .apollo.localization.MeasureState gnss_status = 3 [deprecated = true];
  inline bool has_gnss_status() const PROTOBUF_DEPRECATED;
  inline void clear_gnss_status() PROTOBUF_DEPRECATED;
  static const int kGnssStatusFieldNumber = 3;
  inline ::apollo::localization::MeasureState gnss_status() const PROTOBUF_DEPRECATED;
  inline void set_gnss_status(::apollo::localization::MeasureState value) PROTOBUF_DEPRECATED;

  // optional .apollo.localization.MeasureState lidar_status = 4 [deprecated = true];
  inline bool has_lidar_status() const PROTOBUF_DEPRECATED;
  inline void clear_lidar_status() PROTOBUF_DEPRECATED;
  static const int kLidarStatusFieldNumber = 4;
  inline ::apollo::localization::MeasureState lidar_status() const PROTOBUF_DEPRECATED;
  inline void set_lidar_status(::apollo::localization::MeasureState value) PROTOBUF_DEPRECATED;

  // optional double measurement_time = 5;
  inline bool has_measurement_time() const;
  inline void clear_measurement_time();
  static const int kMeasurementTimeFieldNumber = 5;
  inline double measurement_time() const;
  inline void set_measurement_time(double value);

  // optional string state_message = 6;
  inline bool has_state_message() const;
  inline void clear_state_message();
  static const int kStateMessageFieldNumber = 6;
  inline const ::std::string& state_message() const;
  inline void set_state_message(const ::std::string& value);
  inline void set_state_message(const char* value);
  inline void set_state_message(const char* value, size_t size);
  inline ::std::string* mutable_state_message();
  inline ::std::string* release_state_message();
  inline void set_allocated_state_message(::std::string* state_message);

  // @@protoc_insertion_point(class_scope:apollo.localization.LocalizationStatus)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_fusion_status();
  inline void clear_has_fusion_status();
  inline void set_has_gnss_status();
  inline void clear_has_gnss_status();
  inline void set_has_lidar_status();
  inline void clear_has_lidar_status();
  inline void set_has_measurement_time();
  inline void clear_has_measurement_time();
  inline void set_has_state_message();
  inline void clear_has_state_message();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::common::Header* header_;
  int fusion_status_;
  int gnss_status_;
  double measurement_time_;
  ::std::string* state_message_;
  int lidar_status_;
  friend void  protobuf_AddDesc_localization_2eproto();
  friend void protobuf_AssignDesc_localization_2eproto();
  friend void protobuf_ShutdownFile_localization_2eproto();

  void InitAsDefaultInstance();
  static LocalizationStatus* default_instance_;
};
// ===================================================================


// ===================================================================

// Uncertainty

// optional .apollo.common.Point3D position_std_dev = 1;
inline bool Uncertainty::has_position_std_dev() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Uncertainty::set_has_position_std_dev() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Uncertainty::clear_has_position_std_dev() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Uncertainty::clear_position_std_dev() {
  if (position_std_dev_ != NULL) position_std_dev_->::apollo::common::Point3D::Clear();
  clear_has_position_std_dev();
}
inline const ::apollo::common::Point3D& Uncertainty::position_std_dev() const {
  // @@protoc_insertion_point(field_get:apollo.localization.Uncertainty.position_std_dev)
  return position_std_dev_ != NULL ? *position_std_dev_ : *default_instance_->position_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::mutable_position_std_dev() {
  set_has_position_std_dev();
  if (position_std_dev_ == NULL) position_std_dev_ = new ::apollo::common::Point3D;
  // @@protoc_insertion_point(field_mutable:apollo.localization.Uncertainty.position_std_dev)
  return position_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::release_position_std_dev() {
  clear_has_position_std_dev();
  ::apollo::common::Point3D* temp = position_std_dev_;
  position_std_dev_ = NULL;
  return temp;
}
inline void Uncertainty::set_allocated_position_std_dev(::apollo::common::Point3D* position_std_dev) {
  delete position_std_dev_;
  position_std_dev_ = position_std_dev;
  if (position_std_dev) {
    set_has_position_std_dev();
  } else {
    clear_has_position_std_dev();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.Uncertainty.position_std_dev)
}

// optional .apollo.common.Point3D orientation_std_dev = 2;
inline bool Uncertainty::has_orientation_std_dev() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Uncertainty::set_has_orientation_std_dev() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Uncertainty::clear_has_orientation_std_dev() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Uncertainty::clear_orientation_std_dev() {
  if (orientation_std_dev_ != NULL) orientation_std_dev_->::apollo::common::Point3D::Clear();
  clear_has_orientation_std_dev();
}
inline const ::apollo::common::Point3D& Uncertainty::orientation_std_dev() const {
  // @@protoc_insertion_point(field_get:apollo.localization.Uncertainty.orientation_std_dev)
  return orientation_std_dev_ != NULL ? *orientation_std_dev_ : *default_instance_->orientation_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::mutable_orientation_std_dev() {
  set_has_orientation_std_dev();
  if (orientation_std_dev_ == NULL) orientation_std_dev_ = new ::apollo::common::Point3D;
  // @@protoc_insertion_point(field_mutable:apollo.localization.Uncertainty.orientation_std_dev)
  return orientation_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::release_orientation_std_dev() {
  clear_has_orientation_std_dev();
  ::apollo::common::Point3D* temp = orientation_std_dev_;
  orientation_std_dev_ = NULL;
  return temp;
}
inline void Uncertainty::set_allocated_orientation_std_dev(::apollo::common::Point3D* orientation_std_dev) {
  delete orientation_std_dev_;
  orientation_std_dev_ = orientation_std_dev;
  if (orientation_std_dev) {
    set_has_orientation_std_dev();
  } else {
    clear_has_orientation_std_dev();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.Uncertainty.orientation_std_dev)
}

// optional .apollo.common.Point3D linear_velocity_std_dev = 3;
inline bool Uncertainty::has_linear_velocity_std_dev() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Uncertainty::set_has_linear_velocity_std_dev() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Uncertainty::clear_has_linear_velocity_std_dev() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Uncertainty::clear_linear_velocity_std_dev() {
  if (linear_velocity_std_dev_ != NULL) linear_velocity_std_dev_->::apollo::common::Point3D::Clear();
  clear_has_linear_velocity_std_dev();
}
inline const ::apollo::common::Point3D& Uncertainty::linear_velocity_std_dev() const {
  // @@protoc_insertion_point(field_get:apollo.localization.Uncertainty.linear_velocity_std_dev)
  return linear_velocity_std_dev_ != NULL ? *linear_velocity_std_dev_ : *default_instance_->linear_velocity_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::mutable_linear_velocity_std_dev() {
  set_has_linear_velocity_std_dev();
  if (linear_velocity_std_dev_ == NULL) linear_velocity_std_dev_ = new ::apollo::common::Point3D;
  // @@protoc_insertion_point(field_mutable:apollo.localization.Uncertainty.linear_velocity_std_dev)
  return linear_velocity_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::release_linear_velocity_std_dev() {
  clear_has_linear_velocity_std_dev();
  ::apollo::common::Point3D* temp = linear_velocity_std_dev_;
  linear_velocity_std_dev_ = NULL;
  return temp;
}
inline void Uncertainty::set_allocated_linear_velocity_std_dev(::apollo::common::Point3D* linear_velocity_std_dev) {
  delete linear_velocity_std_dev_;
  linear_velocity_std_dev_ = linear_velocity_std_dev;
  if (linear_velocity_std_dev) {
    set_has_linear_velocity_std_dev();
  } else {
    clear_has_linear_velocity_std_dev();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.Uncertainty.linear_velocity_std_dev)
}

// optional .apollo.common.Point3D linear_acceleration_std_dev = 4;
inline bool Uncertainty::has_linear_acceleration_std_dev() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Uncertainty::set_has_linear_acceleration_std_dev() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Uncertainty::clear_has_linear_acceleration_std_dev() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Uncertainty::clear_linear_acceleration_std_dev() {
  if (linear_acceleration_std_dev_ != NULL) linear_acceleration_std_dev_->::apollo::common::Point3D::Clear();
  clear_has_linear_acceleration_std_dev();
}
inline const ::apollo::common::Point3D& Uncertainty::linear_acceleration_std_dev() const {
  // @@protoc_insertion_point(field_get:apollo.localization.Uncertainty.linear_acceleration_std_dev)
  return linear_acceleration_std_dev_ != NULL ? *linear_acceleration_std_dev_ : *default_instance_->linear_acceleration_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::mutable_linear_acceleration_std_dev() {
  set_has_linear_acceleration_std_dev();
  if (linear_acceleration_std_dev_ == NULL) linear_acceleration_std_dev_ = new ::apollo::common::Point3D;
  // @@protoc_insertion_point(field_mutable:apollo.localization.Uncertainty.linear_acceleration_std_dev)
  return linear_acceleration_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::release_linear_acceleration_std_dev() {
  clear_has_linear_acceleration_std_dev();
  ::apollo::common::Point3D* temp = linear_acceleration_std_dev_;
  linear_acceleration_std_dev_ = NULL;
  return temp;
}
inline void Uncertainty::set_allocated_linear_acceleration_std_dev(::apollo::common::Point3D* linear_acceleration_std_dev) {
  delete linear_acceleration_std_dev_;
  linear_acceleration_std_dev_ = linear_acceleration_std_dev;
  if (linear_acceleration_std_dev) {
    set_has_linear_acceleration_std_dev();
  } else {
    clear_has_linear_acceleration_std_dev();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.Uncertainty.linear_acceleration_std_dev)
}

// optional .apollo.common.Point3D angular_velocity_std_dev = 5;
inline bool Uncertainty::has_angular_velocity_std_dev() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Uncertainty::set_has_angular_velocity_std_dev() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Uncertainty::clear_has_angular_velocity_std_dev() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Uncertainty::clear_angular_velocity_std_dev() {
  if (angular_velocity_std_dev_ != NULL) angular_velocity_std_dev_->::apollo::common::Point3D::Clear();
  clear_has_angular_velocity_std_dev();
}
inline const ::apollo::common::Point3D& Uncertainty::angular_velocity_std_dev() const {
  // @@protoc_insertion_point(field_get:apollo.localization.Uncertainty.angular_velocity_std_dev)
  return angular_velocity_std_dev_ != NULL ? *angular_velocity_std_dev_ : *default_instance_->angular_velocity_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::mutable_angular_velocity_std_dev() {
  set_has_angular_velocity_std_dev();
  if (angular_velocity_std_dev_ == NULL) angular_velocity_std_dev_ = new ::apollo::common::Point3D;
  // @@protoc_insertion_point(field_mutable:apollo.localization.Uncertainty.angular_velocity_std_dev)
  return angular_velocity_std_dev_;
}
inline ::apollo::common::Point3D* Uncertainty::release_angular_velocity_std_dev() {
  clear_has_angular_velocity_std_dev();
  ::apollo::common::Point3D* temp = angular_velocity_std_dev_;
  angular_velocity_std_dev_ = NULL;
  return temp;
}
inline void Uncertainty::set_allocated_angular_velocity_std_dev(::apollo::common::Point3D* angular_velocity_std_dev) {
  delete angular_velocity_std_dev_;
  angular_velocity_std_dev_ = angular_velocity_std_dev;
  if (angular_velocity_std_dev) {
    set_has_angular_velocity_std_dev();
  } else {
    clear_has_angular_velocity_std_dev();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.Uncertainty.angular_velocity_std_dev)
}

// -------------------------------------------------------------------

// LocalizationEstimate

// optional .apollo.common.Header header = 1;
inline bool LocalizationEstimate::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LocalizationEstimate::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LocalizationEstimate::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LocalizationEstimate::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& LocalizationEstimate::header() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationEstimate.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::apollo::common::Header* LocalizationEstimate::mutable_header() {
  set_has_header();
  if (header_ == NULL) header_ = new ::apollo::common::Header;
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationEstimate.header)
  return header_;
}
inline ::apollo::common::Header* LocalizationEstimate::release_header() {
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void LocalizationEstimate::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.LocalizationEstimate.header)
}

// optional .apollo.localization.Pose pose = 2;
inline bool LocalizationEstimate::has_pose() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LocalizationEstimate::set_has_pose() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LocalizationEstimate::clear_has_pose() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LocalizationEstimate::clear_pose() {
  if (pose_ != NULL) pose_->::apollo::localization::Pose::Clear();
  clear_has_pose();
}
inline const ::apollo::localization::Pose& LocalizationEstimate::pose() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationEstimate.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::apollo::localization::Pose* LocalizationEstimate::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) pose_ = new ::apollo::localization::Pose;
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationEstimate.pose)
  return pose_;
}
inline ::apollo::localization::Pose* LocalizationEstimate::release_pose() {
  clear_has_pose();
  ::apollo::localization::Pose* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void LocalizationEstimate::set_allocated_pose(::apollo::localization::Pose* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.LocalizationEstimate.pose)
}

// optional .apollo.localization.Uncertainty uncertainty = 3;
inline bool LocalizationEstimate::has_uncertainty() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LocalizationEstimate::set_has_uncertainty() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LocalizationEstimate::clear_has_uncertainty() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LocalizationEstimate::clear_uncertainty() {
  if (uncertainty_ != NULL) uncertainty_->::apollo::localization::Uncertainty::Clear();
  clear_has_uncertainty();
}
inline const ::apollo::localization::Uncertainty& LocalizationEstimate::uncertainty() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationEstimate.uncertainty)
  return uncertainty_ != NULL ? *uncertainty_ : *default_instance_->uncertainty_;
}
inline ::apollo::localization::Uncertainty* LocalizationEstimate::mutable_uncertainty() {
  set_has_uncertainty();
  if (uncertainty_ == NULL) uncertainty_ = new ::apollo::localization::Uncertainty;
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationEstimate.uncertainty)
  return uncertainty_;
}
inline ::apollo::localization::Uncertainty* LocalizationEstimate::release_uncertainty() {
  clear_has_uncertainty();
  ::apollo::localization::Uncertainty* temp = uncertainty_;
  uncertainty_ = NULL;
  return temp;
}
inline void LocalizationEstimate::set_allocated_uncertainty(::apollo::localization::Uncertainty* uncertainty) {
  delete uncertainty_;
  uncertainty_ = uncertainty;
  if (uncertainty) {
    set_has_uncertainty();
  } else {
    clear_has_uncertainty();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.LocalizationEstimate.uncertainty)
}

// optional double measurement_time = 4;
inline bool LocalizationEstimate::has_measurement_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LocalizationEstimate::set_has_measurement_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LocalizationEstimate::clear_has_measurement_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LocalizationEstimate::clear_measurement_time() {
  measurement_time_ = 0;
  clear_has_measurement_time();
}
inline double LocalizationEstimate::measurement_time() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationEstimate.measurement_time)
  return measurement_time_;
}
inline void LocalizationEstimate::set_measurement_time(double value) {
  set_has_measurement_time();
  measurement_time_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationEstimate.measurement_time)
}

// repeated .apollo.common.TrajectoryPoint trajectory_point = 5;
inline int LocalizationEstimate::trajectory_point_size() const {
  return trajectory_point_.size();
}
inline void LocalizationEstimate::clear_trajectory_point() {
  trajectory_point_.Clear();
}
inline const ::apollo::common::TrajectoryPoint& LocalizationEstimate::trajectory_point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationEstimate.trajectory_point)
  return trajectory_point_.Get(index);
}
inline ::apollo::common::TrajectoryPoint* LocalizationEstimate::mutable_trajectory_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationEstimate.trajectory_point)
  return trajectory_point_.Mutable(index);
}
inline ::apollo::common::TrajectoryPoint* LocalizationEstimate::add_trajectory_point() {
  // @@protoc_insertion_point(field_add:apollo.localization.LocalizationEstimate.trajectory_point)
  return trajectory_point_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::common::TrajectoryPoint >&
LocalizationEstimate::trajectory_point() const {
  // @@protoc_insertion_point(field_list:apollo.localization.LocalizationEstimate.trajectory_point)
  return trajectory_point_;
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::common::TrajectoryPoint >*
LocalizationEstimate::mutable_trajectory_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.localization.LocalizationEstimate.trajectory_point)
  return &trajectory_point_;
}

// optional .apollo.localization.MsfStatus msf_status = 6;
inline bool LocalizationEstimate::has_msf_status() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void LocalizationEstimate::set_has_msf_status() {
  _has_bits_[0] |= 0x00000020u;
}
inline void LocalizationEstimate::clear_has_msf_status() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void LocalizationEstimate::clear_msf_status() {
  if (msf_status_ != NULL) msf_status_->::apollo::localization::MsfStatus::Clear();
  clear_has_msf_status();
}
inline const ::apollo::localization::MsfStatus& LocalizationEstimate::msf_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationEstimate.msf_status)
  return msf_status_ != NULL ? *msf_status_ : *default_instance_->msf_status_;
}
inline ::apollo::localization::MsfStatus* LocalizationEstimate::mutable_msf_status() {
  set_has_msf_status();
  if (msf_status_ == NULL) msf_status_ = new ::apollo::localization::MsfStatus;
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationEstimate.msf_status)
  return msf_status_;
}
inline ::apollo::localization::MsfStatus* LocalizationEstimate::release_msf_status() {
  clear_has_msf_status();
  ::apollo::localization::MsfStatus* temp = msf_status_;
  msf_status_ = NULL;
  return temp;
}
inline void LocalizationEstimate::set_allocated_msf_status(::apollo::localization::MsfStatus* msf_status) {
  delete msf_status_;
  msf_status_ = msf_status;
  if (msf_status) {
    set_has_msf_status();
  } else {
    clear_has_msf_status();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.LocalizationEstimate.msf_status)
}

// optional .apollo.localization.MsfSensorMsgStatus sensor_status = 7;
inline bool LocalizationEstimate::has_sensor_status() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void LocalizationEstimate::set_has_sensor_status() {
  _has_bits_[0] |= 0x00000040u;
}
inline void LocalizationEstimate::clear_has_sensor_status() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void LocalizationEstimate::clear_sensor_status() {
  if (sensor_status_ != NULL) sensor_status_->::apollo::localization::MsfSensorMsgStatus::Clear();
  clear_has_sensor_status();
}
inline const ::apollo::localization::MsfSensorMsgStatus& LocalizationEstimate::sensor_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationEstimate.sensor_status)
  return sensor_status_ != NULL ? *sensor_status_ : *default_instance_->sensor_status_;
}
inline ::apollo::localization::MsfSensorMsgStatus* LocalizationEstimate::mutable_sensor_status() {
  set_has_sensor_status();
  if (sensor_status_ == NULL) sensor_status_ = new ::apollo::localization::MsfSensorMsgStatus;
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationEstimate.sensor_status)
  return sensor_status_;
}
inline ::apollo::localization::MsfSensorMsgStatus* LocalizationEstimate::release_sensor_status() {
  clear_has_sensor_status();
  ::apollo::localization::MsfSensorMsgStatus* temp = sensor_status_;
  sensor_status_ = NULL;
  return temp;
}
inline void LocalizationEstimate::set_allocated_sensor_status(::apollo::localization::MsfSensorMsgStatus* sensor_status) {
  delete sensor_status_;
  sensor_status_ = sensor_status;
  if (sensor_status) {
    set_has_sensor_status();
  } else {
    clear_has_sensor_status();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.LocalizationEstimate.sensor_status)
}

// -------------------------------------------------------------------

// LocalizationStatus

// optional .apollo.common.Header header = 1;
inline bool LocalizationStatus::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LocalizationStatus::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LocalizationStatus::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LocalizationStatus::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& LocalizationStatus::header() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationStatus.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::apollo::common::Header* LocalizationStatus::mutable_header() {
  set_has_header();
  if (header_ == NULL) header_ = new ::apollo::common::Header;
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationStatus.header)
  return header_;
}
inline ::apollo::common::Header* LocalizationStatus::release_header() {
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void LocalizationStatus::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.LocalizationStatus.header)
}

// optional .apollo.localization.MeasureState fusion_status = 2;
inline bool LocalizationStatus::has_fusion_status() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LocalizationStatus::set_has_fusion_status() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LocalizationStatus::clear_has_fusion_status() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LocalizationStatus::clear_fusion_status() {
  fusion_status_ = 0;
  clear_has_fusion_status();
}
inline ::apollo::localization::MeasureState LocalizationStatus::fusion_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationStatus.fusion_status)
  return static_cast< ::apollo::localization::MeasureState >(fusion_status_);
}
inline void LocalizationStatus::set_fusion_status(::apollo::localization::MeasureState value) {
  assert(::apollo::localization::MeasureState_IsValid(value));
  set_has_fusion_status();
  fusion_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationStatus.fusion_status)
}

// optional .apollo.localization.MeasureState gnss_status = 3 [deprecated = true];
inline bool LocalizationStatus::has_gnss_status() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LocalizationStatus::set_has_gnss_status() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LocalizationStatus::clear_has_gnss_status() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LocalizationStatus::clear_gnss_status() {
  gnss_status_ = 0;
  clear_has_gnss_status();
}
inline ::apollo::localization::MeasureState LocalizationStatus::gnss_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationStatus.gnss_status)
  return static_cast< ::apollo::localization::MeasureState >(gnss_status_);
}
inline void LocalizationStatus::set_gnss_status(::apollo::localization::MeasureState value) {
  assert(::apollo::localization::MeasureState_IsValid(value));
  set_has_gnss_status();
  gnss_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationStatus.gnss_status)
}

// optional .apollo.localization.MeasureState lidar_status = 4 [deprecated = true];
inline bool LocalizationStatus::has_lidar_status() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void LocalizationStatus::set_has_lidar_status() {
  _has_bits_[0] |= 0x00000008u;
}
inline void LocalizationStatus::clear_has_lidar_status() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void LocalizationStatus::clear_lidar_status() {
  lidar_status_ = 0;
  clear_has_lidar_status();
}
inline ::apollo::localization::MeasureState LocalizationStatus::lidar_status() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationStatus.lidar_status)
  return static_cast< ::apollo::localization::MeasureState >(lidar_status_);
}
inline void LocalizationStatus::set_lidar_status(::apollo::localization::MeasureState value) {
  assert(::apollo::localization::MeasureState_IsValid(value));
  set_has_lidar_status();
  lidar_status_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationStatus.lidar_status)
}

// optional double measurement_time = 5;
inline bool LocalizationStatus::has_measurement_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void LocalizationStatus::set_has_measurement_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void LocalizationStatus::clear_has_measurement_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void LocalizationStatus::clear_measurement_time() {
  measurement_time_ = 0;
  clear_has_measurement_time();
}
inline double LocalizationStatus::measurement_time() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationStatus.measurement_time)
  return measurement_time_;
}
inline void LocalizationStatus::set_measurement_time(double value) {
  set_has_measurement_time();
  measurement_time_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationStatus.measurement_time)
}

// optional string state_message = 6;
inline bool LocalizationStatus::has_state_message() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void LocalizationStatus::set_has_state_message() {
  _has_bits_[0] |= 0x00000020u;
}
inline void LocalizationStatus::clear_has_state_message() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void LocalizationStatus::clear_state_message() {
  if (state_message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    state_message_->clear();
  }
  clear_has_state_message();
}
inline const ::std::string& LocalizationStatus::state_message() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationStatus.state_message)
  return *state_message_;
}
inline void LocalizationStatus::set_state_message(const ::std::string& value) {
  set_has_state_message();
  if (state_message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    state_message_ = new ::std::string;
  }
  state_message_->assign(value);
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationStatus.state_message)
}
inline void LocalizationStatus::set_state_message(const char* value) {
  set_has_state_message();
  if (state_message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    state_message_ = new ::std::string;
  }
  state_message_->assign(value);
  // @@protoc_insertion_point(field_set_char:apollo.localization.LocalizationStatus.state_message)
}
inline void LocalizationStatus::set_state_message(const char* value, size_t size) {
  set_has_state_message();
  if (state_message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    state_message_ = new ::std::string;
  }
  state_message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:apollo.localization.LocalizationStatus.state_message)
}
inline ::std::string* LocalizationStatus::mutable_state_message() {
  set_has_state_message();
  if (state_message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    state_message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:apollo.localization.LocalizationStatus.state_message)
  return state_message_;
}
inline ::std::string* LocalizationStatus::release_state_message() {
  clear_has_state_message();
  if (state_message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = state_message_;
    state_message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void LocalizationStatus::set_allocated_state_message(::std::string* state_message) {
  if (state_message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete state_message_;
  }
  if (state_message) {
    set_has_state_message();
    state_message_ = state_message;
  } else {
    clear_has_state_message();
    state_message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.localization.LocalizationStatus.state_message)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace localization
}  // namespace apollo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::localization::MeasureState> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::MeasureState>() {
  return ::apollo::localization::MeasureState_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_localization_2eproto__INCLUDED
